# These environment variables must be set in CircleCI UI
#
# DOCKER_EMAIL   - login info for docker hub
# DOCKER_USER
# DOCKER_PASS
#
# Read the README for more information.
version: 2
jobs:
  build:
    # Variable expansion in working_directory not supported at this time
    # You will need to modify the code below to reflect your github account/repo setup
    working_directory: /go/src/github.com/danahmed1997/hw9_2
    docker:
      - image: circleci/golang:1.11
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
      - run: echo 'simple change again again a different hash???'
      - run: echo 'export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"' >> $BASH_ENV
      - run: echo 'export GOPATH_BASE="${GOPATH_HEAD}/src/github.com/${CIRCLE_PROJECT_USERNAME}"' >> $BASH_ENV
      - run: echo 'export DOCKER_REPO="$(if [ ${CIRCLE_PROJECT_USERNAME} == 'Securing-DevOps' ]; then echo securingdevops; else echo $DOCKER_USER; fi)"' >> $BASH_ENV
      - run: mkdir -p "${GOPATH_BASE}"
      - run: mkdir -p "${GOPATH_HEAD}/bin"
      - run: go get github.com/govend/govend

      - run:
          name: Build application container
          command: |
            go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
            [ ! -e bin ] && mkdir bin;
            cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/deployer;
            docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;

      - deploy:
          # Push application container to dockerhub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
                docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
            fi
